services:
  builder:
    image: maven:3.9.8-amazoncorretto-17
    container_name: java_app_builder_bank_app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: mvn clean package

  app:
    image: openjdk:17-jdk-slim
    container_name: BankingApp-0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    volumes:
      - ./target/SberBank-0.0.1-SNAPSHOT.jar:/app/SberBank-0.0.1-SNAPSHOT.jar
    entrypoint: ["java", "-jar", "/app/BankingApp-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - builder
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

  db:
    image: postgres:13
    container_name: postgres_db_bank_app
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: