spring:
  application:
    name: SberBank
  datasource:
    url: jdbc:postgresql://db:5432/mydatabase
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:

      hibernate:
        format_sql: true
        use_sql_comments: true

